### ISSUE TITLE
Table view includes spurious extra column "total_rows"

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cdb-manager#51]
![screenshot_64](https://user-images.githubusercontent.com/113883/41552195-e9ab022e-72e2-11e8-9aff-677b279975a1.png)

Perhaps the `total_rows` attribute is being mistakenly pulled in from the JSON response.

**Comment by danicarrion** [comment]
Should be fixed now, and as a bonus now you can see the total number of items in the top right corner :-)
